global:
  scrape_timeout: 5s
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
- alert.rules
scrape_configs:
- job_name: prometheus
  honor_labels: true
  static_configs:
  - targets:
    - cadvisor:8080
    - mikrotik-exporter:9436

